### ISSUE TITLE
Feature-Request

### ISSUE THREAD

**Issue by KutalmisBercin** [NREL/SOWFA-6#11]
Dear @mchurchf @DriesAllaerts @ewquon ,

I wanted to ask for your permission/assent on whether I can transfer some of the methods/functionalities from your SOWFA work (by acknowledging you wherever possible) into the official OpenFOAM development line (OpenFOAM v2006-v2012, and so on [openfoam.com variant]).

I am aware of the fact that OpenFOAM licence allows users to use/modify codes without requesting any approval, yet I always contact the real contributors first.

I would greatly appreciate your feedback.

Many thanks for your time.

Kutalmis

**Comment by DriesAllaerts** [comment]
Dear @KutalmisBercin,

I'm not opposed to transferring some of the functionality of SOWFA to the official OpenFOAM development line. I can only speak for myself as I'm no longer part of the NREL organization, but I presume that @mchurchf and @ewquon will approve as well.

Best regards
Dries Allaerts

**Comment by KutalmisBercin** [comment]
Dear @DriesAllaerts ,

Many thanks for your reply and consent.
Kutalmis

**Comment by ewquon** [comment]
Dear @KutalmisBercin,

I don't see any issue with transferring functionality either. Which features were you interested in, specifically? 

Cheers,
Eliot

**Comment by mchurchf** [comment]
@KutalmisBercin,

Yes, feel free to transfer functionality.  We have experimented with using SOWFA with the OpenFOAM.com line, and you may have to make a few minor changes, but you should be able to get it to work.

Matt Churchfield

**Comment by KutalmisBercin** [comment]
Dear @ewquon and @mchurchf ,

Many thanks for your approval. Highly appreciated.

@ewquon , Pretty much every functionality that SOWFA has, prioritised in relation to the priorities of the industry. Please do not hesitate to contact me, if need be, via kbc__at _esi-group.com , if you would have any further questions, or suggestions in this regard.

Thank you very much again.

Kind regards,
Kutalmis

**Comment by Hosein-F** [comment]
Dear @ewquon and @mchurchf ,

I am going to install SOWFA-6.  I have downloaded SOWFA-6 from "https://github.com/NREL/SOWFA-6/tree/dev".

I have installed OpenFOAM-6 from "https://openfoamwiki.net/index.php/Installation/Linux/OpenFOAM-6/Ubuntu#Ubuntu_16.04" too.

the versions of gcc, gfortran and g++ in my ubuntu16.04.7LTS are 5.5.0 20171010.

The structure of my folders are as follow:

OpenFOAM-6 directory:"/home/hosein_falahaty/OpenFOAM/OpenFOAM-6"
ThirdParty-6 directory:"/home/hosein_falahaty/OpenFOAM/ThirdParty-6"
SOWFA-6 directory:"/home/hosein_falahaty/OpenFOAM/hosein_falahaty-6/SOWFA-6".
OpenFAST directory:"/home/hosein_falahaty/OpenFAST".
(I have to mention that the OpenFAST is not installed successfully. But since I don't need coupling between aerodynamics and structural response at this stage I'd like to ignore it (please correct me if I'm wrong). I'm just going to do micro-siting).

I have attached the bashrc of OpenFAOM and bash_profile of SOWFA.

Unfortunately, still I have not been successful in installing SOWFA (the error log file is attached). I will appreciate a lot if you can help me in this regard. It should be noted that I don't run Allwmake in root mode.

Thank you in advance.

Best regards,

Hosein


[Allwmake01.error.txt](https://github.com/NREL/SOWFA-6/files/6102889/Allwmake01.error.txt)
[bashrc.txt](https://github.com/NREL/SOWFA-6/files/6102890/bashrc.txt)
[bash_profile.txt](https://github.com/NREL/SOWFA-6/files/6102892/bash_profile.txt)

**Comment by DriesAllaerts** [comment]
Dear @Hosein-F ,

I think you're having issues because you are not setting a couple of environment variables that are used when compiling SOWFA. The variables are $SOWFA_APPBIN and $SOWFA_LIBBIN. Check out lines 65-71 in the [environment script](https://github.com/NREL/SOWFA-6/blob/dev/environmentScripts/OF-6-env-gcc-central) that comes with SOWFA versus the SOWFA-6 function in your own bash_profile. I'd suggest you update your bash_profile and try again.

That said, note that this closed feature request is probably not the right place to ask for help.

Best regards,
Dries

**Comment by Hosein-F** [comment]
Dear @ DriesAllaerts

Thank you for your comments. Sorry I didn't notice that this feature request is closed.

Best regards.
