### ISSUE TITLE
Installation guidelines for SOWFA-6

### ISSUE THREAD

**Issue by danielgonro** [NREL/SOWFA-6#27]
Hi there.
I´m trying to install the SOWFA-6 version but the information in the repository is very confuse. For example,   the readme file it says to use only the OpenFOAM 6 version but in the bash_profile it is declare the 2.4.0 version.
It will be very helpful a similar guideline for the SOWFA-6 version. I know this version is still under development but i would like to use it and help a little bit with my experience to improve it.

Best Regards 

Daniel

**Comment by rthedin** [comment]
Hi Daniel,
Installation instructions for SOWFA-6 are analogous to those of SOWFA 2.4. Some of files present in this repository may not be up-to-date with paths to version 6 of OpenFOAM. Adapt the paths as needed and try to compile it– you should not run into major issues.

-Regis

**Comment by danielgonro** [comment]
Dear Regis, thank you very much for your response.
I´d tried to install this version of SOWFA by following those instructions for the 2.4.0 version, however i´m facing several errors.
The first one is when i´m clonnig using the SOWFA-6 github, for some reason is clonning a dev directory without the SOWFA code. Only in the dev-tree is available a code version of SOWFA. Here https://github.com/NREL/SOWFA-6/tree/dev
However, there is no bash_profile file in there, and in the method i found for the SOWFA 2.4.0 there are som editing there too.

Sorry if these issues are too simple but i can´t found a solution to them.

Best Regards

Daniel

**Comment by rthedin** [comment]
Daniel,
As far as the cloning goes, if you are having issues with that, you can always use the web interface to download the branch and then send manually to your computing cluster.

In SOWFA-6, there is an `environmentScripts` directory which contains the environment script that you need. There is some editing needed there so you can adapt it to your machine/system and your paths. That file is fairly easy to read and understand what is being set, but essentially, it is loading what is needed, sourcing OpenFOAM's `bashrc` and then setting paths. That should make the compilation of SOWFA work, placing the binaries within `$SOWFA_DIR` and making those binaries available since `$PATH` and `$LD_LIBRARY_PATH` are also updated.

-Regis

**Comment by cjwan12589** [comment]
Hello, how should I run the files in the environment variables folder to set the environment variables?
